EdiApiClient use Vostok.ClusterClient
skbkontur/edi-api-client pull request #9
Opened 2021-05-14 06:08 UTC by skozulin

2021-05-14 07:40 UTC, Anton92nd requested changes

2021-05-14 07:40 UTC, Anton92nd commented on EdiApi.Client/Http/Connectors/TransformerConnectorEdiApiClient.cs
> +            var request = BuildPostRequest("V1/Connectors/Transformers/TransformationStarted", null, authToken, Array.Empty<byte>())
Плохо, когда непонятно, что это за параметры, в которые передаём `null` и `Array.Empty<byte>()`. Можно конечно прописывать явно имена у них, но я бы сделал немного по-другому. Все параметры кроме `url` сделать параметрами с дефолтным значением `null` и добавить такую перегрузку:
```
protected virtual Request BuildPostRequest([NotNull] string relativeUrl, AuthCredentials authCredentials = null, string authToken = null)
            => BuildPostRequest(relativeUrl, authCredentials, authToken, Array.Empty<byte>());
```

Здесь соответственно стало бы так
`BuildPostRequest("V1/Connectors/Transformers/TransformationStarted", authToken: authToken)`

Аналогично для `BuildGetRequest`

2021-05-14 07:40 UTC, Anton92nd commented on EdiApi.Client/Http/Connectors/TransformerConnectorEdiApiClient.cs
> +            boxEventBatch.Events = boxEventBatch.Events ?? new TransformerConnectorBoxEvent[0];
Выделить в метод копипасту. Вроде точь-в-точь одинаковое все.

2021-05-14 07:40 UTC, Anton92nd commented on EdiApi.Client/Http/HttpClientException.cs
> +                throw new HttpClientException(message, statusCode);
В юзадже исключение и так бросается. Кажется метод `Create` не должен бросать, только создавать.

2021-05-14 07:40 UTC, Anton92nd commented on EdiApi.Client/Http/Messages/MessagesEdiApiHttpClient.cs
> +        public MessagesEdiApiHttpClient(string apiClientId, string environment, int timeoutInMilliseconds = DefaultTimeout, IWebProxy proxy = null, bool enableKeepAlive = true)
Для публичной апишки все таки тоже решил сделать?

2021-05-14 07:40 UTC, Anton92nd commented on EdiApi.Client/Http/Messages/MessagesEdiApiHttpClient.cs
> +            var boxEventBatch = Serializer.Deserialize<MessageBoxEventBatch>(result.Response.Content.ToString());
И здесь снова копируется кусок кода. Отличие видимо только в `boxEventTypeRegistry`

2021-05-14 07:40 UTC, Anton92nd commented on EdiApi.Client/Http/Messages/MessagesEdiApiHttpClient.cs
> +            var boxEventBatch = Serializer.Deserialize<MessageBoxEventBatch>(result.Response.Content.ToString());
И тут

2021-05-14 07:42 UTC, Anton92nd commented on EdiApi.Client/Http/Connectors/TransformerConnectorEdiApiClient.cs
> +            boxEventBatch.Events = boxEventBatch.Events ?? new TransformerConnectorBoxEvent[0];
Раньше причем был метод `GetEvents` выделен для этого

2021-05-14 08:07 UTC, Anton92nd requested changes

2021-05-14 08:07 UTC, Anton92nd commented on EdiApi.Client/Http/ClusterClientFactory.cs
> +            return new ClusterClient(log, configuration =>
В нашем `GroboClusterClient` еще происходит `configuration.SetupDistributedKonturTracing()`. Может тут тоже надо? Провалился в `SetupSingular`, там ничего похожего не нашёл.

2021-05-14 08:21 UTC, Anton92nd commented on EdiApi.Client/Http/ClusterClientFactory.cs
> +            return new ClusterClient(log, configuration =>
Без трассировок снитч не будет метрики рисовать.

2021-05-15 03:07 UTC, skozulin commented on EdiApi.Client/EdiApi.Client.csproj
> +    <PackageReference Update="Nerdbank.GitVersioning" Version="3.4.194" />
Исправил

2021-05-15 03:13 UTC, skozulin commented on EdiApi.Client/Http/BaseEdiApiHttpClient.cs
> +            int timeoutInMilliseconds, IWebProxy proxy = null, bool enableKeepAlive = true)
Убрал

2021-05-15 04:47 UTC, skozulin commented on EdiApi.Client/Http/BaseEdiApiHttpClient.cs
>          [NotNull]
Перевел на #nullable enable , Annotations - удалил

2021-05-17 11:50 UTC, Anton92nd commented on EdiApi.Client/Http/HttpClientException.cs
> +        public ResponseCode StatusCode { get; }
В сообщении статус код не видно будет. Может лучше явно включить?

2021-05-18 14:22 UTC, skozulin commented on EdiApi.Client/Http/Connectors/TransformerConnectorEdiApiClient.cs
> +            var request = BuildPostRequest("V1/Connectors/Transformers/TransformationStarted", null, authToken, Array.Empty<byte>())
Согласен, так более читабельно, поправил

2021-05-18 14:56 UTC, skozulin commented on EdiApi.Client/Http/HttpClientException.cs
> +                throw new HttpClientException(message, statusCode);
Ох... да, че-та я рефлекторно прихреначил здесь throw, исправил

2021-05-18 14:57 UTC, skozulin commented on EdiApi.Client/Http/Messages/MessagesEdiApiHttpClient.cs
> +        public MessagesEdiApiHttpClient(string apiClientId, string environment, int timeoutInMilliseconds = DefaultTimeout, IWebProxy proxy = null, bool enableKeepAlive = true)
Да, чтоб униформно было

2021-05-18 15:02 UTC, skozulin commented on EdiApi.Client/Http/HttpClientException.cs
> +        public ResponseCode StatusCode { get; }
Тогда обратная совместимость потеряется по тексту сообщения. И раньше же этот код никто не видел - кажется лучше так оставить.

2021-05-19 06:07 UTC, skozulin commented on EdiApi.Client/Http/ClusterClientFactory.cs
> +            return new ClusterClient(log, configuration =>
`SetupDistributedKonturTracing` bcgjkmpetn `KonturTracer` из `Vostok.Tracing.Kontur` и это не доступно во внешнем nugete,  наверно можно оставить такую зависимость, чтоб подсунуть контуровский трейсер - но что-то сомневаюсь, что кто-то осознанно его заюзает :(

2021-05-19 06:31 UTC, skozulin commented on EdiApi.Client/Http/Connectors/TransformerConnectorEdiApiClient.cs
> +            boxEventBatch.Events = boxEventBatch.Events ?? new TransformerConnectorBoxEvent[0];
Да, заинлайнил , т.к. всего пара строк и удобнее смотреть когда постобработка рядом... Но думаю можно и вытащить в отдельный метод - вытащил.

2021-05-19 06:31 UTC, Anton92nd commented on EdiApi.Client/Http/ClusterClientFactory.cs
> +            return new ClusterClient(log, configuration =>
Ок, не подумал об этом.

2021-05-19 06:45 UTC, skozulin commented on EdiApi.Client/Http/Messages/MessagesEdiApiHttpClient.cs
> +            var boxEventBatch = Serializer.Deserialize<MessageBoxEventBatch>(result.Response.Content.ToString());
Вынес в отдельный метод

2021-05-19 06:45 UTC, skozulin commented on EdiApi.Client/Http/Messages/MessagesEdiApiHttpClient.cs
> +            var boxEventBatch = Serializer.Deserialize<MessageBoxEventBatch>(result.Response.Content.ToString());
Вынес в отдельный метод

2021-05-19 12:40 UTC, Anton92nd approved these changes

2021-05-24 07:41 UTC, merged